version: '3.1'

services:

  pg:
    image: postgres
    restart: always
    ports:
      - 5422:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - pg_volume:/var/lib/postgresql/data

volumes:
  pg_volume:
